//! Re-exports Rust modules generated by `prost` from `.proto` files at build time.
//! These types serve as the serialization layer and are imported throughout the
//! codebase via `use crate::proto::*`.

pub mod entry {
    include!(concat!(env!("OUT_DIR"), "/entry.rs"));
}
pub mod table {
    include!(concat!(env!("OUT_DIR"), "/table.rs"));
}
pub mod delta {
    include!(concat!(env!("OUT_DIR"), "/delta.rs"));
}
pub mod injected {
    include!(concat!(env!("OUT_DIR"), "/injected.rs"));
}
pub mod patch {
    include!(concat!(env!("OUT_DIR"), "/patch.rs"));
}
pub mod state {
    include!(concat!(env!("OUT_DIR"), "/state.rs"));
}
pub mod update {
    include!(concat!(env!("OUT_DIR"), "/update.rs"));
}
pub mod block {
    include!(concat!(env!("OUT_DIR"), "/block.rs"));
}
pub mod cell {
    include!(concat!(env!("OUT_DIR"), "/cell.rs"));
}
